# -*- coding: utf-8 -*-
"""BDA IA2 code .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gyf0jQJaRst11653o-sEVdvaTmJRnEem
"""

import cv2
import numpy as np
from ultralytics import YOLO
import winsound
import threading
import json
from datetime import datetime
import matplotlib.pyplot as plt

# ===============================
# LOAD YOLO MODEL
# ===============================
model = YOLO("yolov8m.pt")

# ===============================
# CONFIGURATION
# ===============================
CONF_THRESHOLD = 0.30
PERSON_AREA_MIN = 5000
TIGER_AREA_MIN = 20000

# ===============================
# THREAT VARIABLES
# ===============================
previous_distance = None
threat_score = 0
alarm_active = False
frame_count = 0

# ===============================
# DATA STORAGE (For JSON + Graph)
# ===============================
time_series_data = []
threat_history = []
frame_history = []

# ===============================
# ENABLE LIVE GRAPH
# ===============================
plt.ion()
fig, ax = plt.subplots()

# ===============================
# ALARM FUNCTION
# ===============================
def trigger_alarm():
    global alarm_active
    if not alarm_active:
        alarm_active = True
        print("🚨 CRITICAL THREAT! ALARM TRIGGERED!")
        try:
            winsound.Beep(1000, 1500)
            winsound.Beep(1000, 1500)
        except:
            pass
        alarm_active = False

# ===============================
# OPEN WEBCAM
# ===============================
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Webcam not accessible.")
    exit()

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

print("Human–Wildlife Conflict Prediction System Running...")
print("Press Q to exit")

# ===============================
# MAIN LOOP
# ===============================
while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame, imgsz=640)

    human_box = None
    animal_box = None
    distance = None

    for r in results:
        for box in r.boxes:
            label = model.names[int(box.cls)]
            conf = float(box.conf)

            if conf < CONF_THRESHOLD:
                continue

            x1, y1, x2, y2 = map(int, box.xyxy[0])
            area = (x2 - x1) * (y2 - y1)

            # HUMAN
            if label == "person" and area >= PERSON_AREA_MIN:
                human_box = (x1, y1, x2, y2)
                color = (0, 0, 255)
                text = f"HUMAN {conf:.2f}"

            # TIGER (cat workaround)
            elif label == "cat" and area >= TIGER_AREA_MIN:
                animal_box = (x1, y1, x2, y2)
                color = (0, 140, 255)
                text = f"TIGER {conf:.2f}"

            # OTHER ANIMALS
            elif label in ["dog", "cow", "horse", "elephant", "bear", "zebra"]:
                animal_box = (x1, y1, x2, y2)
                color = (0, 255, 0)
                text = f"{label.upper()} {conf:.2f}"

            else:
                continue

            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
            cv2.putText(frame, text,
                        (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.7, color, 2)

    # ===============================
    # THREAT CALCULATION
    # ===============================
    if human_box and animal_box:
        hx1, hy1, hx2, hy2 = human_box
        ax1, ay1, ax2, ay2 = animal_box

        hx_center = (hx1 + hx2) // 2
        hy_center = (hy1 + hy2) // 2
        ax_center = (ax1 + ax2) // 2
        ay_center = (ay1 + ay2) // 2

        distance = np.sqrt((hx_center - ax_center)**2 +
                           (hy_center - ay_center)**2)

        cv2.line(frame,
                 (hx_center, hy_center),
                 (ax_center, ay_center),
                 (255,255,255), 2)

        if distance < 200:
            threat_score += 2
        elif distance < 350:
            threat_score += 1

        if previous_distance and distance < previous_distance:
            threat_score += 1

        previous_distance = distance
    else:
        previous_distance = None

    # Threat decay
    threat_score = max(threat_score - 0.5, 0)

    # ===============================
    # THREAT LEVEL
    # ===============================
    if threat_score < 2:
        level = "SAFE"
        level_color = (0,255,0)
    elif threat_score < 5:
        level = "MODERATE"
        level_color = (0,255,255)
    elif threat_score < 8:
        level = "HIGH"
        level_color = (0,165,255)
    else:
        level = "CRITICAL"
        level_color = (0,0,255)
        threading.Thread(target=trigger_alarm).start()

    # ===============================
    # STORE TIME-SERIES DATA
    # ===============================
    time_series_data.append({
        "frame": frame_count,
        "threat_score": round(threat_score, 2),
        "threat_level": level,
        "distance": round(distance, 2) if distance else None
    })

    threat_history.append(threat_score)
    frame_history.append(frame_count)

    # ===============================
    # UPDATE LIVE GRAPH (every 10 frames)
    # ===============================
    if frame_count % 10 == 0:
        ax.clear()
        ax.plot(frame_history, threat_history, color='red')
        ax.set_xlabel("Frame")
        ax.set_ylabel("Threat Score")
        ax.set_title("Threat Escalation Over Time")
        ax.set_ylim(0, 15)
        plt.pause(0.001)

    cv2.putText(frame,
                f"THREAT LEVEL: {level} | SCORE: {int(threat_score)}",
                (30,50),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                level_color,
                3)

    frame_count += 1

    cv2.imshow("Human–Wildlife Conflict Prediction System", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# ===============================
# SAVE JSON (Graph Included)
# ===============================
output_data = {
    "timestamp": datetime.now().isoformat(),
    "total_frames": frame_count,
    "time_series": time_series_data
}

with open("detection_output.json", "w") as f:
    json.dump(output_data, f, indent=2)

# ===============================
# SAVE FINAL GRAPH IMAGE
# ===============================
plt.ioff()
plt.figure()
plt.plot(frame_history, threat_history, color='red')
plt.xlabel("Frame")
plt.ylabel("Threat Score")
plt.title("Threat Escalation Over Time")
plt.savefig("threat_graph.png")

print("\n✅ Files saved:")
print(" - detection_output.json (contains full graph data)")
print(" - threat_graph.png (final threat curve image)")
print(f"Total frames processed: {frame_count}")